name: devicelocale
description: A Flutter package that can be used to extract the locales that are currently defined on a device with the current locale set as the first in the list.
version: 0.2.2
author: Steve Rogers <srogers.uk@gmail.com>
homepage: https://github.com/magnatronus/flutter-devicelocale

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.devicelocale
    pluginClass: DevicelocalePlugin

dev_dependencies:
  test: ^1.3.0
  mockito: 3.0.0
  flutter_test:
    sdk: flutter
    
environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"